import weka.core.Instance;
import weka.core.Instances;

/** Class providing static methods to calculate various performance metrics for a classifier
 */
public class EvaluationTools {

    /** Calculates the accuracy of the results generated from a classifier
     * Assumes that the parameters are of equal length
     *
     * @param data the test cases from the dataset as an Instances object
     * @param results an array containing the predicted classes generated by the classifier for this dataset
     * @return the accuracy as a double
     */
    public static double calculateAccuracy(Instances data, double[] results){
        int correct = 0;
        for (int i = 0; i < results.length; i++){
            if (results[i] == data.get(i).classValue()){
                correct++;
            }
        }
        return (double) correct / (double) results.length;
    }

    /** Forms a confusion matrix from the results generated by a classifier
     *
     * @param data the test cases from the dataset as an Instances object
     * @param results an array containing the predicted classes generated by the classifier for this dataset
     * @return the confusionMatrix as a matrix of doubles
     */
    public static double[][] makeConfusionMatrix(Instances data, double[] results){
        int c = results.length - 1;
        double[][] confusionMatrix = new double[c][c];

        for (int i = 0; i < c; i++){
            int predicted = (int) results[i];
            int actual;
            Instance instance = data.instance(i);
            if (instance.classValue() != 0.0){
                actual = 1;
            }
            else {
                actual = 0;
            }
            confusionMatrix[predicted][actual] += 1;
        }
        return confusionMatrix;
    }

    /** Calculates the true positive rate from a confusionMatrix
     *
     * @param confusionMatrix the confusionMatrix generated for a classifiers results on a dataset
     * @return the true positive rate
     */
    public static double calculateTPR(double[][] confusionMatrix){
        return confusionMatrix[0][0]/(confusionMatrix[0][0] + confusionMatrix[0][1]);
    }

    /** Calculates the true negative rate from a confusionMatrix
     *
     * @param confusionMatrix the confusionMatrix generated for a classifiers results on a dataset
     * @return the true negative rate
     */
    public static double calculateTNR(double[][] confusionMatrix){
        double tnr;
        if (confusionMatrix[1][0] + confusionMatrix[1][1] == 0){
            tnr = 0;
        }
        else {
            tnr = confusionMatrix[1][1]/(confusionMatrix[1][0] + confusionMatrix[1][1]);
        }
        return tnr;
    }

    /** Calculates the balanced accuracy with the values ascertained from a confusion matrix
     *
     * @param tpr the true positive rate
     * @param tnr the true negative rate
     * @return the balanced accuracy as a double
     */
    public static double calculateBalancedAccuracy(double tpr, double tnr){
        return (tpr + tnr)/2;
    }

}
